name: Build and test
on:
  pull_request: { }
jobs:
  build-and-test:
    name: Run tests on ${{ matrix.os }}
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java environment
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11

      - name: Build
        id: build
        run: mvn -B -U "-Dsurefire.rerunFailingTestsCount=5" clean install

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Unit Test Results ${{ matrix.os }}
          path: target/surefire-reports/
          retention-days: 7

  publish-test-results:
      name: Publish Unit Test Results
      runs-on: ubuntu-latest
      needs: build-and-test
      if: always()

      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v2
          with:
            path: artifacts

        - name: Publish Unit Test Results
          uses: EnricoMi/publish-unit-test-result-action@v1.26
          with:
            files: artifacts/**/*.xml

